# Generated by Django 5.1.1 on 2024-11-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0003_passwordresetuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetuser',
            options={},
        ),
        migrations.RenameField(
            model_name='passwordresetuser',
            old_name='otp_created',
            new_name='otp_created_at',
        ),
        migrations.RenameField(
            model_name='passwordresetuser',
            old_name='otp_secretly_key',
            new_name='otp_secret_key',
        ),
        migrations.RemoveField(
            model_name='passwordresetuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='passwordresetuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='passwordresetuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='passwordresetuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='passwordresetuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='passwordresetuser',
            name='username',
        ),
    ]
