# Generated by Django 5.1.1 on 2024-11-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0008_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='Image'),
        ),
    ]
